[opener]
edit =[{ run = '${EDITOR:=helix} "$@"', block = true, for = "linux"}]
open = [{ run = 'helix "$@"', block = true, for = "linux" }]

[open]
rules = [
  { mime = "text/*", use = [ "edit" ] }
]
