[[language]]
name="rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer]
command = "rust-analyzer"


[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }


[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports"}

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
roots = ["pyproject.toml"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

# [language.formatter]
# command = "ruff"
# args = ["format", "--line-length", "120"]

[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]
